Added small image
ryanjon2040/Discord-UE4 pull request #6
Opened 2020-09-09 22:02 UTC by MrKuBu

Small image discord RPC

2020-09-09 22:11 UTC, ryanjon2040 requested changes
Thank you for the PR. I made some comments on the changes.

2020-09-09 22:11 UTC, ryanjon2040 commented on Source/DiscordUE4/Private/DiscordObject.cpp
> +	activity.GetAssets().SetLargeImage(TCHAR_TO_UTF8(*InKeyName));
Shouldn't this be Set Small Image?

2020-09-09 22:11 UTC, ryanjon2040 commented on Source/DiscordUE4/Private/DiscordObject.cpp
> +			DiscordObjectInstance->OnSmallImageSet.Broadcast(static_cast<EDiscordReturnResult>(ResultByte));
OnSmallImageSer delegate is missing in header.

2020-09-09 22:32 UTC, MrKuBu commented
ActivityAssets.LargeImage  - Large image
ActivityAssets.SmallImage  - Small image
ActivityAssets.LargeText  - Large image description (mouse pointing image)
ActivityAssets.SmallText  - Small image description (mouse pointing image)

2020-09-09 22:36 UTC, MrKuBu commented
Can add sln file for build?

2020-09-17 06:54 UTC, ryanjon2040 commented
@MrKuBu I have merged the changes from other two PRs so I'm closing this one.

2020-09-17 06:54 UTC, closed without merging